name: Add new aka.ms link
description: Use this form to submit an aka.ms link to the aka.cmd.ms search database.
title: "New aka.ms link "
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thank you for taking the time to submit a new aka.ms link to aka.cmd.ms!
        
        A few notes:
        * It will take a few minutes after you submit for the link to appear on aka.cmd.ms.
        * Avoid submitting links that are not meant for public use.
        * Submit a pull request to make advanced edits such as updating the title, deleting an entry for [aka.ms config](https://github.com/merill/aka/tree/main/website/config)
  - type: input
    id: link
    attributes:
      label: Aka.ms link name
      description: Feel free to omit the aka.ms part of the url. Please avoid submitting links that are internal to Microsoft.
      placeholder: ex. intune
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category (Optional. Select None to auto-select)
      description: The category will allow the link to be grouped with other products. To add a new category, edit [this file](https://github.com/merill/aka/edit/main/.github/ISSUE_TEMPLATE/add-link.yaml) and submit a pull request.
      options:
        - azure
        - azuread
        - defender
        - graph
        - dynamics365
        - intune
        - microsoft365
        - powerplatform
        - windows365
    validations:
      required: false
