on:
  issues:
    types:
      - opened

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          
  validate_and_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-link.yaml
          
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}'
