on:
  issues:
    types:
      - opened

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          
  update_issue:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Process new link request
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PowerShellForGitHub
          . ./build/scripts/AkaUtils.ps1
          Set-AkaGitHubAuth
          New-AkaLinkFromIssue -issueNumber ${{ github.event.issue.number }}